import { renderWeekNumbersHtml } from "./week-numbers-html.mjs";
import { renderReflectionHtml } from "./bar-html.mjs";
import { renderBarsHtml, renderAppHeaderHtml } from "./bar-html.mjs";

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function areaLabel(r) {
  return r.emoji ? `${r.emoji} ${r.label}` : r.label;
}

function renderAllocationSectionHtml(result) {
  const copy = result.observeCopy?.allocation || {};
  const chartRows = result.chartAllocation || result.allocation;
  const bars = renderBarsHtml(chartRows);
  const fullList = (result.fullBreakdown || result.allocation)
    .map(
      (r) =>
        `<li><span class="breakdown-emoji" aria-hidden="true">${r.emoji || ""}</span> <span>${escapeHtml(r.label)}: <strong>${r.hours}h</strong> <span class="pct">(${r.percent}%)</span></span></li>`
    )
    .join("");

  return `
    <section class="allocation-section" aria-labelledby="alloc-heading">
      <p class="section-eyebrow">${escapeHtml(copy.eyebrow || "Time flies, but…")}</p>
      <h2 id="alloc-heading">${escapeHtml(copy.title || "Where did time go this week?")}</h2>
      ${bars || "<p class='note'>No timed events in this range.</p>"}
      <details class="full-detail">
        <summary>Full breakdown</summary>
        <ul class="full-list breakdown-list">${fullList}</ul>
      </details>
    </section>`;
}

function renderInsightsHtml(insights) {
  return insights
    .map((c) => {
      const kind =
        c.id?.includes("celebrate") || c.id === "pm_life_celebrate"
          ? "celebrate"
          : c.id?.includes("sleep") || c.id?.includes("rest") || c.id?.includes("unscheduled")
            ? "alarm"
            : "";
      return `
      <article class="insight${kind ? ` insight--${kind}` : ""}">
        <p class="insight-text">${escapeHtml(c.text)}</p>
        <p class="insight-id">${escapeHtml(c.id)}</p>
      </article>`;
    })
    .join("");
}

export function buildHtmlReport(result) {
  const insights = renderInsightsHtml(result.insights);
  const reflection = renderReflectionHtml(result.weekFrom, result.weekTo);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(result.branding?.titleLine || "I'm Time")} — ${escapeHtml(result.week)}</title>
  <link rel="stylesheet" href="/styles/tokens.css" />
  <link rel="stylesheet" href="/styles/report.css" />
</head>
<body>
  <div class="wrap">
    ${renderAppHeaderHtml(result, result.branding)}
    ${renderAllocationSectionHtml(result)}
    ${renderWeekNumbersHtml(result)}
    <section aria-labelledby="insights-heading">
      <h2 id="insights-heading">Insight cards</h2>
      ${insights || "<p class='note'>No strong patterns this week.</p>"}
    </section>
    ${reflection}
    <p class="note">Generated by <code>pnpm analyze</code>.</p>
  </div>
  <script type="module">
    import { bindReflection } from "/js/render-reflection.js";
    bindReflection("${result.weekFrom}", "${result.weekTo}");
    document.querySelectorAll("[data-threshold-editors] input").forEach((input) => {
      const key = input.dataset.thresholdKey;
      if (!key) return;
      const saved = localStorage.getItem(key);
      if (saved) input.value = saved;
      input.addEventListener("change", () => localStorage.setItem(key, input.value));
    });
  </script>
</body>
</html>`;
}
