import { renderWeekNumbersHtml } from "./week-numbers-html.mjs";
import { renderBarsHtml, renderAppHeaderHtml, renderReflectionHtml } from "./bar-html.mjs";

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function areaLabel(r) {
  return r.emoji ? `${r.emoji} ${r.label}` : r.label;
}

function renderInsightsHtml(insights) {
  return insights
    .map((c) => {
      const kind =
        c.id === "pm_life_celebrate"
          ? "celebrate"
          : c.id?.includes("sleep")
            ? "alarm"
            : "";
      return `
      <article class="insight${kind ? ` insight--${kind}` : ""}">
        <p class="insight-text">${escapeHtml(c.text)}</p>
        <p class="insight-id">${escapeHtml(c.id)}</p>
      </article>`;
    })
    .join("");
}

export function buildHtmlReport(result) {
  const chartRows = result.chartAllocation || result.allocation;
  const bars = renderBarsHtml(chartRows);
  const fullList = result.allocation
    .map((r) => `<li>${escapeHtml(areaLabel(r))}: <strong>${r.hours}h</strong> (${r.percent}%)</li>`)
    .join("");

  const insights = renderInsightsHtml(result.insights);
  const reflection = renderReflectionHtml(result.weekFrom, result.weekTo);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(result.branding?.titleLine || "I'm Time")} — ${escapeHtml(result.week)}</title>
  <link rel="stylesheet" href="/styles/tokens.css" />
  <link rel="stylesheet" href="/styles/report.css" />
</head>
<body>
  <div class="wrap">
    ${renderAppHeaderHtml(result, result.branding)}

    <section aria-labelledby="alloc-heading">
      <h2 id="alloc-heading">Where your timed hours went</h2>
      ${bars || "<p class='note'>No timed events in this range.</p>"}
      <p class="note donut-hint">Bar fill = Google legend color · width = share of the ${result.weekHours}h week.</p>
      <details class="full-detail">
        <summary>Full breakdown</summary>
        <ul class="full-list">${fullList}</ul>
      </details>
    </section>

    ${renderWeekNumbersHtml(result)}

    <section aria-labelledby="insights-heading">
      <h2 id="insights-heading">Insight cards</h2>
      ${insights || "<p class='note'>No strong patterns this week.</p>"}
    </section>

    ${reflection}

    <p class="note">Generated by <code>pnpm analyze</code>. Mapping: config/calendar-colors.json</p>
  </div>
  <script type="module">
    import { bindReflection } from "/js/render-reflection.js";
    bindReflection("${result.weekFrom}", "${result.weekTo}");
    const input = document.getElementById("sleep-threshold-input");
    if (input) {
      const key = "imtime-sleep-threshold-hours";
      const saved = localStorage.getItem(key);
      if (saved) input.value = saved;
      input.addEventListener("change", () => localStorage.setItem(key, input.value));
    }
  </script>
</body>
</html>`;
}
